version: '3'
services:
  app:
    build: ./src
    volumes:
      - ./src:/usr/src/app
      - ./src/scrape_test:/tmp/scrape_test
  test:
    build: ./test
    command: bash -c 'python3 manage.py runserver 0.0.0.0:5000'
    ports:
      - '5000:5000'
    volumes:
      - ./test:/usr/src/test
    restart: always
